name: Deploy su Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: 2222
          script: |
            echo "Starting..." >> /home/sthor69/logging
            cd /home/sthor69/workspace/smarthome_php/
            git pull origin main
            sudo rsync -av --exclude='sensor_data.db' --exclude='.git/' --exclude='.github/' --exclude='var/' --exclude='logs/' . /var/www/smarthome/
            cd /var/www/smarthome
            sudo ./fix_permissions.sh
